import { TheaterEvent, Ticket, SpecialGuestEntry } from "./types";

export const INITIAL_EVENTS: TheaterEvent[] = [
  {
    id: "evt-gala-inaugural-25",
    title: "Gala Privada Inaugural: Reapertura del Teatro Municipal",
    tagline: "Función de honor y homenaje al patrimonio cultural",
    date: "2026-09-25",
    time: "19:00",
    durationMinutes: 120,
    mode: "SEATED_NUMBERED",
    status: "ACTIVE",
    isPrivate: true,
    totalCapacity: 190,
    plantaBajaCapacity: 120,
    balconCapacity: 70,
    vipRowsPlantaBaja: ["A"],
    vipRowsBalcon: ["K"],
    registrationEnabled: true,
    description: "Concierto de gala y reapertura oficial de la sala patrimonial. Acceso exclusivo para invitados especiales, autoridades y delegaciones mediante invitación directa y lista de protocolo.",
    location: "Sala Principal, Teatro Municipal",
  },
  {
    id: "evt-sinfonica-26",
    title: "Concierto de Otoño: Orquesta Sinfónica Municipal",
    tagline: "Obras clásicas universales y autores contemporáneos",
    date: "2026-09-26",
    time: "18:30",
    durationMinutes: 105,
    mode: "SEATED_NUMBERED",
    status: "ACTIVE",
    isPrivate: false,
    totalCapacity: 190,
    plantaBajaCapacity: 120,
    balconCapacity: 70,
    vipRowsPlantaBaja: ["A"],
    vipRowsBalcon: ["K"],
    registrationEnabled: true,
    description: "Presentación especial de la Orquesta Sinfónica Municipal. Entrada gratuita con reserva previa de butaca numerada. Los asientos no reclamados 10 min antes se liberan para público en espera.",
    location: "Sala Principal, Teatro Municipal",
  },
  {
    id: "evt-titeres-27",
    title: "Festival Familiar de Artes Escénicas y Títeres",
    tagline: "Función comunitaria para toda la familia",
    date: "2026-09-27",
    time: "16:00",
    durationMinutes: 75,
    mode: "GENERAL_ADMISSION",
    status: "ACTIVE",
    isPrivate: false,
    totalCapacity: 190,
    plantaBajaCapacity: 120,
    balconCapacity: 70,
    vipRowsPlantaBaja: [],
    vipRowsBalcon: [],
    registrationEnabled: true,
    description: "Obra de títeres gigantes y comedia musical. Acceso general gratuito por orden de llegada con aforo dinámico hasta completar capacidad.",
    location: "Sala Principal, Teatro Municipal",
  },
];

export const INITIAL_SPECIAL_GUESTS: SpecialGuestEntry[] = [
  {
    id: "sp-01",
    eventId: "evt-gala-inaugural-25",
    name: "Despacho de Alcaldía Municipal",
    citizenId: "1-0842-0391",
    seatId: "PB-A-06",
    ticketsCount: 2,
    notes: "Invitación de Honor - Fila A Presidencial",
    redeemedCount: 0,
  },
  {
    id: "sp-02",
    eventId: "evt-gala-inaugural-25",
    name: "Concejo Municipal y Regiduría",
    citizenId: null,
    seatId: null,
    ticketsCount: 8,
    notes: "Reserva de bloque institucional (sin nombres asociados aún)",
    redeemedCount: 2,
  },
  {
    id: "sp-03",
    eventId: "evt-gala-inaugural-25",
    name: "Dra. Sofía Valverde (Dirección de Patrimonio)",
    citizenId: "1-1120-0456",
    seatId: "PB-A-08",
    ticketsCount: 1,
    notes: "Conferencista y arquitecta restauradora",
    redeemedCount: 1,
  },
  {
    id: "sp-04",
    eventId: "evt-gala-inaugural-25",
    name: "Delegación Ministerio de Cultura",
    citizenId: null,
    seatId: null,
    ticketsCount: 6,
    notes: "Cupos de cortesía oficial para viceministerio y acompañantes",
    redeemedCount: 0,
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: "tkt-001",
    eventId: "evt-gala-inaugural-25",
    citizenName: "Dra. Sofía Valverde",
    citizenId: "1-1120-0456",
    citizenPhone: "8844-1234",
    seatId: "PB-A-08",
    seatLabel: "Platea A-08",
    zone: "PLANTA_BAJA",
    qrCodeValue: "TM-TKT-001-GALA-PB-A-08",
    isVipGuest: true,
    checkedIn: true,
    checkedInAt: "2026-09-25T18:42:00Z",
    createdAt: "2026-09-23T10:00:00Z",
  },
  {
    id: "tkt-002",
    eventId: "evt-gala-inaugural-25",
    citizenName: "Don Alberto Méndez Ramos",
    citizenId: "1-0532-0988",
    citizenPhone: "8312-9900",
    seatId: "PB-B-05",
    seatLabel: "Platea B-05",
    zone: "PLANTA_BAJA",
    qrCodeValue: "TM-TKT-002-GALA-PB-B-05",
    isVipGuest: false,
    checkedIn: false,
    checkedInAt: null,
    createdAt: "2026-09-23T11:20:00Z",
  },
  {
    id: "tkt-003",
    eventId: "evt-sinfonica-26",
    citizenName: "Mariana Rojas Castro",
    citizenId: "2-0741-0852",
    citizenPhone: "8999-3322",
    seatId: "PB-C-06",
    seatLabel: "Platea C-06",
    zone: "PLANTA_BAJA",
    qrCodeValue: "TM-TKT-003-SINF-PB-C-06",
    isVipGuest: false,
    checkedIn: false,
    checkedInAt: null,
    createdAt: "2026-09-23T12:00:00Z",
  },
];
